apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: kuberenetes.io/Opaque  # Opaque is the default Secret type if you don't explicitly specify a type in a Secret manifest.
data:
  db-pass: dnByb2RicGFzcw== # base64 encoded password (echo -n "vprodbpass" | base64)
  rmq-pass: Z3Vlc3Q= # base64 encoded password (echo -n "guest" | base64)